version: 1
disable_existing_loggers: False

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: app.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    formatter: detailed

formatters:
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s - %(name)s - [%(levelname)s] - %(message)s'
    log_colors:
      DEBUG: blue
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

loggers:
  root:
    level: INFO
    handlers: [console, file]
  asyncssh:
    level: WARNING
    handlers: [console, file]
  asyncio:
    level: INFO
    handlers: [console, file]
  